### ISSUE TITLE
Responsive header on mobile screens.

### ISSUE THREAD

**Issue by RocktimSaikia** [rishabh-bansal/GitStart#3770]
* I noticed that in small screens ,the header specially the github follow button and logo goes down and it kind of breaks the design flow :

![bug](https://user-images.githubusercontent.com/33410545/66268321-20817380-e7f1-11e9-94eb-4fe0c0a78254.png) .

* Also i see you are using pre defined github buttons but you can actually remove the name and only stick with "Follow" on the button which looks much nicer.

So this is the final result i'm suggesting :

![fixed](https://user-images.githubusercontent.com/33410545/66268427-262b8900-e7f2-11e9-8dfa-da90a4ffff56.png)

#### So if you approve with these fixes , can i make a pull request with these changes ?

**Comment by rishabh-bansal** [comment]
@RocktimSaikia Feel free to make a pull request! :)
