### ISSUE TITLE
This repository is excluded from Hacktoberfest as it doesn't align with their core values.

### ISSUE THREAD

**Issue by sanjaypradeep** [rishabh-bansal/GitStart#3867]

**Comment by kurisu-gh** [comment]
Yes, confirmed here as well. The owner should put a message on the README to clarify that pull requests on this repo will not count towards Hacktoberfest.

In fact the Hacktoberfest team already put an issue up in https://github.com/rishabh-bansal/GitStart/issues/3812 explaining the situation but the owner closed the issue so it's not visible by default, and I guess most beginners will not realize this.
